version: '3.8'

services:
  dbmysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=meriem # Vérifie si ce mot de passe est correct
      - MYSQL_DATABASE=stationSki
    ports:
      - "3308:3306" # Expose le port MySQL
    volumes:
      - db_data:/var/lib/mysql
  app-station-ski:
    depends_on:
      - dbmysql

    image:  meriemboubaker/gestion-station-ski:1.0.0 #nom du repository fil dockerhub est meriemboubaker
    restart: on-failure
    ports:
      - "8089:8089"
    volumes:
      - app_logs:/app/logs
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:mysql://dbmysql:3306/stationSki?createDatabaseIfNotExist=true&useSSL=false",
         "spring.datasource.username": "root",
         "spring.datasource.password": "meriem",
         "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
         "spring.jpa.hibernate.ddl-auto": "update" 
       }'
    stdin_open: true
    tty: true

volumes:
  db_data:
  app_logs: