version: "3.8"
services:
  mysqldb:
    image: mysql
    container_name:  c577c7cba3bb_gestion-station-ski1_dbmysql_1
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=stationSki
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  springboot:
    image: meriemboubaker/gestion-station-ski:1.0.0
    restart: unless-stopped
    ports:
      - "8089:8089"

    depends_on:
      - mysqldb

